name: pytest

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@master
      - name: Install dependencies and run tests
        run: |
          pip install -r requirements.txt
          pytest